/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uas.view;

/**
 *
 * @author DANIEL
 */
public class DetailPengaduan extends javax.swing.JPanel {

    /**
     * Creates new form DataPengaduan
     */
    public DetailPengaduan() {
        initComponents();
    }
    
    // Getter methods for form fields
    public javax.swing.JTextField getNomorPengaduanTextField() {
        return nomorPengaduanTextField;
    }

    public javax.swing.JTextField getTanggalTextField() {
        return tanggalTextField;
    }

    public javax.swing.JTextField getNamaPelaporTextField() {
        return namaPelaporTextField;
    }

    public javax.swing.JTextField getJabatanTextField() {
        return jabatanTextField;
    }

    public javax.swing.JComboBox<String> getLokasiComboBox() {
        return lokasiComboBox;
    }

    public javax.swing.JTextArea getDescTextArea() {
        return descTextArea;
    }

    public javax.swing.JTextArea getCatatanPetugasTextArea() {
        return catatanPetugasTextArea;
    }

    public javax.swing.JLabel getFotoLabel() {
        return fotoLabel;
    }

    public javax.swing.JRadioButton getDiajukanRadioButton() {
        return diajukanRadioButton;
    }

    public javax.swing.JRadioButton getDiprosesRadioButton() {
        return diprosesRadioButton;
    }

    public javax.swing.JRadioButton getSelesaiRadioButton() {
        return selesaiRadioButton;
    }

    public javax.swing.JButton getSaveButton() {
        return saveButton;
    }

    public javax.swing.JButton getResetButton() {
        return resetButton;
    }

    public javax.swing.JButton getBackButton() {
        return backButton;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nomorPengaduanTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tanggalTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaPelaporTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jabatanTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lokasiComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        diajukanRadioButton = new javax.swing.JRadioButton();
        diprosesRadioButton = new javax.swing.JRadioButton();
        selesaiRadioButton = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        catatanPetugasTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        fotoLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1040, 720));
        setMinimumSize(new java.awt.Dimension(1040, 720));
        setPreferredSize(new java.awt.Dimension(1040, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Detail Pengaduan");

        jLabel5.setText("Nomor Pengaduan:");

        nomorPengaduanTextField.setEditable(false);
        nomorPengaduanTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nomorPengaduanTextField.setEnabled(false);

        jLabel10.setText("Tanggal Pengaduan:");

        tanggalTextField.setEditable(false);
        tanggalTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tanggalTextField.setEnabled(false);

        jLabel2.setText("Nama Pelapor:");

        namaPelaporTextField.setEditable(false);
        namaPelaporTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        namaPelaporTextField.setEnabled(false);

        jLabel3.setText("Jabatan:");

        jabatanTextField.setEditable(false);
        jabatanTextField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jabatanTextField.setEnabled(false);

        jLabel6.setText("Lokasi Kerusakan");

        lokasiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kantin", "Gedung 1", "Gedung 2", "Gedung 3", "Basement", " " }));
        lokasiComboBox.setEnabled(false);

        jLabel9.setText("Status:");

        statusButtonGroup.add(diajukanRadioButton);
        diajukanRadioButton.setText("Sedang diajukan");

        statusButtonGroup.add(diprosesRadioButton);
        diprosesRadioButton.setText("Sedang diproses");

        statusButtonGroup.add(selesaiRadioButton);
        selesaiRadioButton.setText("Selesai diproses");
        selesaiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiRadioButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Deskripsi:");

        descTextArea.setEditable(false);
        descTextArea.setColumns(20);
        descTextArea.setRows(5);
        descTextArea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        descTextArea.setEnabled(false);
        jScrollPane1.setViewportView(descTextArea);

        jLabel12.setText("Catatan dari petugas:");

        catatanPetugasTextArea.setColumns(20);
        catatanPetugasTextArea.setRows(5);
        jScrollPane2.setViewportView(catatanPetugasTextArea);

        jLabel8.setText("Foto:");

        fotoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        saveButton.setText("Save");

        resetButton.setText("Reset");

        backButton.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(nomorPengaduanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tanggalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addComponent(namaPelaporTextField)
                            .addComponent(jLabel3)
                            .addComponent(jabatanTextField)
                            .addComponent(jLabel6)
                            .addComponent(selesaiRadioButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(diajukanRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(diprosesRadioButton))
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane2)
                            .addComponent(lokasiComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(fotoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomorPengaduanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tanggalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPelaporTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jabatanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lokasiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diajukanRadioButton)
                            .addComponent(diprosesRadioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selesaiRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(resetButton)
                    .addComponent(backButton))
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selesaiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selesaiRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextArea catatanPetugasTextArea;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JRadioButton diajukanRadioButton;
    private javax.swing.JRadioButton diprosesRadioButton;
    private javax.swing.JLabel fotoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jabatanTextField;
    private javax.swing.JComboBox<String> lokasiComboBox;
    private javax.swing.JTextField namaPelaporTextField;
    private javax.swing.JTextField nomorPengaduanTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton selesaiRadioButton;
    private javax.swing.ButtonGroup statusButtonGroup;
    private javax.swing.JTextField tanggalTextField;
    // End of variables declaration//GEN-END:variables
}
