/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package uas.view;

import javax.swing.*;
import uas.controller.SubmitPengaduanController;
import uas.database.Database;

/**
 * FormPengaduan adalah panel untuk mengirim pengaduan kerusakan barang.
 * Menyediakan input untuk nomor pengaduan, nama pelapor, jabatan, lokasi kerusakan, dan deskripsi kerusakan.
 * Terdapat tombol untuk mengirim pengaduan, mengunggah foto, dan mereset form.
 * 
 * @author DANIEL
 */
public class FormPengaduan extends javax.swing.JPanel {
    
    private final MainFrame mainFrame;

    /**
     * Membuat form pengaduan baru
     * @param mainFrame frame utama aplikasi
     */
    public FormPengaduan(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        addListeners();
        
        // Set default kode pengaduan
        Database db = Database.getInstance();
        nomorPengaduanTextField.setText(db.generateNextKodeLaporan());
        
        // Mengatur fokus awal pada panel utama atau komponen lain
        this.setFocusable(true);
        this.requestFocusInWindow();
        
        locationComboBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomorPengaduanTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namaPelaporTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        posisiTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox<>();
        uploadButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deskripsiTextArea = new javax.swing.JTextArea();
        kirimButton = new javax.swing.JButton();
        resetFormButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(799, 532));
        setMinimumSize(new java.awt.Dimension(799, 532));
        setPreferredSize(new java.awt.Dimension(799, 532));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Form Pengaduan Kerusakan Barang");

        jLabel2.setText("Nomor Pengaduan");

        nomorPengaduanTextField.setEditable(false);
        nomorPengaduanTextField.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("*Harap catat kode ini untuk melakukan pengecekan sendiri melalui kolom pencarian.");

        jLabel4.setText("Nama Pelapor");

        jLabel5.setText("Jabatan");

        jLabel6.setText("Lokasi Kerusakan");

        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kantin", "Gedung 1", "Gedung 2", "Gedung 3", "Basement", " " }));

        uploadButton.setText("Upload Foto");

        jLabel7.setText("Deskripsi");

        deskripsiTextArea.setColumns(20);
        deskripsiTextArea.setRows(5);
        jScrollPane1.setViewportView(deskripsiTextArea);

        kirimButton.setText("Kirim");

        resetFormButton.setText("Reset Form");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homepage.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(uploadButton)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(nomorPengaduanTextField)
                                .addComponent(jLabel4)
                                .addComponent(namaPelaporTextField)
                                .addComponent(posisiTextField)
                                .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(kirimButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetFormButton))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomorPengaduanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPelaporTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(posisiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uploadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel8)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kirimButton)
                    .addComponent(resetFormButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Menambahkan listener ke tombol-tombol dalam form.
     */
    private void addListeners() {
        SubmitPengaduanController controller = new SubmitPengaduanController(this);
        kirimButton.addActionListener(controller);
        uploadButton.addActionListener(controller);
        resetFormButton.addActionListener(controller);
    }
    
    /**
     * Mereset form pengaduan ke keadaan awal.
     */
    public void resetForm() {
        namaPelaporTextField.setText("");
        posisiTextField.setText("");
        locationComboBox.setSelectedIndex(-1);
        deskripsiTextArea.setText("");
        Database db = Database.getInstance();
        nomorPengaduanTextField.setText(db.generateNextKodeLaporan());
    }
    
    // Getter methods for buttons
    public JButton getKirimButton() {
        return kirimButton;
    }

    public JButton getUploadButton() {
        return uploadButton;
    }

    public JButton getResetFormButton() {
        return resetFormButton;
    }

    // Getter methods for form fields
    public JTextField getNomorPengaduanTextField() {
        return nomorPengaduanTextField;
    }

    public JTextField getNamaPelaporTextField() {
        return namaPelaporTextField;
    }

    public JTextField getPosisiTextField() {
        return posisiTextField;
    }

    public JComboBox<String> getLocationComboBox() {
        return locationComboBox;
    }

    public JTextArea getDeskripsiTextArea() {
        return deskripsiTextArea;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea deskripsiTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kirimButton;
    private javax.swing.JComboBox<String> locationComboBox;
    private javax.swing.JTextField namaPelaporTextField;
    private javax.swing.JTextField nomorPengaduanTextField;
    private javax.swing.JTextField posisiTextField;
    private javax.swing.JButton resetFormButton;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
