/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas.view;

import uas.controller.SwitchToHomeController;
import uas.controller.SwitchToFormPengaduanController;
import uas.controller.SwitchToLoginController;
import uas.model.User;

/**
 *
 * @author DANIEL
 */
public class MainFrame extends javax.swing.JFrame {
    private User currentUser; // Tambahkan variabel untuk menyimpan pengguna yang sedang login

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setContentPane(new Home(this));
        pack();
        setLocationRelativeTo(null);
        
        addListeners();
    }
    
    public void setCurrentUser(User user) {
        this.currentUser = user;
    }

    public User getCurrentUser() {
        return currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navMenuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        pengaduanMenu = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(799, 532));
        setResizable(false);

        homeMenu.setText("Home");
        navMenuBar.add(homeMenu);

        pengaduanMenu.setText("Form Pengaduan");
        navMenuBar.add(pengaduanMenu);

        loginMenu.setText("Login");
        navMenuBar.add(loginMenu);

        setJMenuBar(navMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 799, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void addListeners() {
        homeMenu.addMouseListener(new SwitchToHomeController(this));
        loginMenu.addMouseListener(new SwitchToLoginController(this));
        pengaduanMenu.addMouseListener(new SwitchToFormPengaduanController(this));
    }
    
    public void switchToDashboard() {
        Dashboard dashboard = new Dashboard(this);
        this.setVisible(false); // Hide MainFrame
        dashboard.setVisible(true); // Show Dashboard
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenu loginMenu;
    private javax.swing.JMenuBar navMenuBar;
    private javax.swing.JMenu pengaduanMenu;
    // End of variables declaration//GEN-END:variables
}
